"""Dependency-light task-specific contract instances."""

from .franka_pick_place import (
    CAMERA_HEIGHT,
    CAMERA_WIDTH,
    CONTROL_HZ,
    DEFAULT_INSTRUCTION,
    DEFAULT_INSTRUCTION_ID,
    DEFAULT_INSTRUCTION_LANGUAGE,
    FRANKA_PICK_PLACE_ACTION_SCHEMA,
    FRANKA_PICK_PLACE_OBSERVATION_SCHEMA,
    ROBOT_NAME,
    SCENE_NAME,
    TASK_NAME,
)

__all__ = [
    "CAMERA_HEIGHT",
    "CAMERA_WIDTH",
    "CONTROL_HZ",
    "DEFAULT_INSTRUCTION",
    "DEFAULT_INSTRUCTION_ID",
    "DEFAULT_INSTRUCTION_LANGUAGE",
    "FRANKA_PICK_PLACE_ACTION_SCHEMA",
    "FRANKA_PICK_PLACE_OBSERVATION_SCHEMA",
    "ROBOT_NAME",
    "SCENE_NAME",
    "TASK_NAME",
]
